kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-Deployment
  labels:
    app: kavya
    dev: darsh
spec:
  selector:
    matchLabels:
      app: kavya
      dev: darsh
  template:
    metadata:
      labels:
        app: kavya
        dev: darsh
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80


